# -------------------------------
# comments example
# -------------------------------
name: Run-tests-on-any-Push-event_to_master
# Запуск при любом push евенте в ветку master
on:
  push:
    branches:
      - master
jobs:
  prepare_for_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Simple example
        run: echo "Hello, world!" 
