# ------------------------
# ATTENTION:
# каждый новый job чистит рабочее пространство
# ------------------------

name: Run-tests-on-any-Push-event-to-master
# Запуск при любом push евенте в ветку master
on:
  push:
    branches:
      - main
# create job for working
jobs:
  prepare_for_tests:
    # будем выполнять инструкции на ВМ на последней версии ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Python instaling
      # Чекаутим код
        uses: actions/checkout@v2
      
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
        
        # Устанавливаем python coverage для отображения тестового покрытия
      - name: Install python coverage
        run: pip install coverage
          
      - name: Run tests
        run: coverage run tests.py && coverage report -m
        
        # если нужно отдебажить выполнение инструкций
        # стандартные методы:
        # run: |
             # ls -l -a &&
             # pwd &&
             # python tests.py -v
    
