# -------------------------------
# comments example
# -------------------------------
name: Run-tests-on-any-Push-event_to_master
# Запуск при любом push евенте в ветку master
on:
  push:
    branches:
      - main
jobs:
  prepare_for_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Python instaling
      
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
          
  run_tests:
    runs-on: ubuntu-latest
    needs: [prepare_for_tests]
    
    steps:
    # Чекаутим код
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
             ls -l -a &&
             cd Computer-Technology-tasks-4-sem-MIPT &&
             pwd &&
             python tests.py -v
